targets:
  instance: ${TEST_URL:http://localhost:8088}
  camunda: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}

azure:
  servicebus:
    connection-string: ${AZURE_SERVICE_BUS_CONNECTION_STRING}
    topic-name: ${AZURE_SERVICE_BUS_TOPIC_NAME}
    subscription-Name: ${AZURE_SERVICE_BUS_SUBSCRIPTION_NAME}
    retry-duration: ${AZURE_SERVICE_BUS_RETRY_DURATION:60}
    threads: ${AZURE_SERVICE_BUS_CONCURRENT_SESSIONS:1}
    enableASB: ${AZURE_SERVICE_BUS_FEATURE_TOGGLE:false}
    retry-attempts: ${AZURE_SERVICE_BUS_RETRY_ATTEMPTS:0}
