targets:
  instance: ${TEST_URL:http://localhost:8088}
  camunda: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}

azure:
  host: Endpoint=sb://wa-case-handler-servicebus-dev.servicebus.windows.net/;SharedAccessKeyName=SendAndRecieveCCDMessage;SharedAccessKey=8gA8KcaE/e1bBMSVmYE2jaFYMwCkoLhsfTsqn7aJoqs=
  username: SendAndRecieveCCDMessage
  password: 8gA8KcaE/e1bBMSVmYE2jaFYMwCkoLhsfTsqn7aJoqs=
  topic: wa-case-handler-topic-sessions-ft
  subscription: wa-case-handler-topic-sessions-ft-sub
  numberOfConcurrentSessions: 11

enableServiceBus: false
