targets:
  instance: ${TEST_URL:http://localhost:8088}
  camunda: ${CAMUNDA_URL:http://camunda-bpm/engine-rest}

spring.flyway.enabled: false

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ia_timed_event_service
    username: sa
    password:
    platform: h2

azure:
  host: ${AZURE_SERVICE_BUS_HOST}
  username: ${AZURE_SHARED_POLICY_KEY}
  password: ${AZURE_SHARED_POLICY_KEY_SECRET}
  topic: ${AZURE_TOPIC_NAME}
  subscription: ${AZURE_SUBSCRIPTION_NAME}
  numberOfConcurrentSessions: ${AZURE_CONCURRENT_SESSIONS}
  enableASB: ${AZURE_SERVICE_BUS_TOGGLE:false}
