logging.level.uk.gov.hmcts.reform.wacaseeventhandler.clients.*: DEBUG
logging.level.uk.gov.hmcts.reform: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full


spring.jackson.serialization.indent_output: true

idam:
  test:
    username: ${TEST_WA_LAW_FIRM_USERNAME:some_user@hmcts.net}
    password: ${TEST_WA_LAW_FIRM_PASSWORD:password}
