logging.level.uk.gov.hmcts.reform.wacaseeventhandler.clients.*: DEBUG
logging.level.uk.gov.hmcts.reform: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full


spring.jackson.serialization.indent_output: true
