logging.level.org.springframework.web: debug
logging.level.uk.gov.hmcts.reform: debug

feign:
  client:
    config:
      default:
        loggerLevel: full


spring.jackson.serialization.indent_output: true

