server:
  port: 8088

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_CASE_EVENT_HANDLER:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_CASE_EVENT_HANDLER:wa_case_event_handler}
  s2s-authorised:
    services: ${WA_S2S_AUTHORIZED_SERVICES:ccd,ccd_data,ccd_gw,ccd_ps}

wa-workflow-api:
  url: ${WA_WORKFLOW_API_URL:http://localhost:8099}

spring:
  application:
    name: WA Case Event Handler
  jackson.serialization.indent_output: true

govUkHolidays:
  url: https://www.gov.uk/


amqp:
  host: ${AMQP_HOST:ccd-servicebus-demo.servicebus.windows.net}
  username: ${AMQP_USERNAME:SendAndRecieveCCDMessage}
  password: ${AMQP_PASSWORD:eYfgBSLzEi0dijBMpvfBWw7kC8CTPkLXZLgeuUiKXZ0=}
  topic: ${TOPIC_NAME:wa-case-event-handler-topic}
  subscription: ${SUBSCRIPTION_NAME:wa-case-event-handler-subscription-aat}
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: ${TRUST_ALL_CERTS:false}
