logging.level.uk.gov.hmcts.reform.wacaseeventhandler.clients.*: DEBUG
logging.level.uk.gov.hmcts.reform: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: full
management:
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState, CEHLivenessHealthController
        readiness:
          include: readinessState, CEHReadinessHealthController
      show-components: always
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring.jackson.serialization.indent_output: true
