spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:11:///databasename
  main:
    allow-bean-definition-overriding: true

messageProcessing:
  pollIntervalSeconds: 3