server:
  port: 8088

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_CASE_EVENT_HANDLER:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_CASE_EVENT_HANDLER:wa_case_event_handler}
  s2s-authorised:
    services: ${WA_S2S_AUTHORIZED_SERVICES:ccd,ccd_data,ccd_gw,ccd_ps}

wa-workflow-api:
  url: ${WA_WORKFLOW_API_URL:http://localhost:8099}

spring:
  application:
    name: WA Case Event Handler
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_NAME:wa_case_event_handler}${POSTGRES_CONNECTION_OPTIONS:}
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:}
    properties:
      charSet: UTF-8
  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: ${POSTGRES_NAME:wa_case_event_handler}
  jackson:
    serialization:
      indent_output: true

govUkHolidays:
  url: https://www.gov.uk/

azure:
  host: ${AZURE_SERVICE_BUS_HOST}
  username: ${AZURE_SHARED_POLICY_KEY}
  password: ${AZURE_SHARED_POLICY_KEY_SECRET}
  topic: ${AZURE_TOPIC_NAME}
  subscription: ${AZURE_SUBSCRIPTION_NAME}
  numberOfConcurrentSessions: ${AZURE_CONCURRENT_SESSIONS}
  enableASB: ${AZURE_SERVICE_BUS_TOGGLE:false}
