server:
  port: 8088

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

idam:
  s2s-auth:
    url: ${S2S_URL:http://service-auth-provider-api}
    secret: ${S2S_SECRET_CASE_EVENT_HANDLER:AAAAAAAAAAAAAAAA}
    name: ${S2S_NAME_CASE_EVENT_HANDLER:wa_case_event_handler}
  s2s-authorised:
    services: ${WA_S2S_AUTHORIZED_SERVICES:ccd,ccd_data,ccd_gw,ccd_ps}

wa-workflow-api:
  url: ${WA_WORKFLOW_API_URL:http://localhost:8099}

spring:
  application:
    name: WA Case Event Handler
  jackson.serialization.indent_output: true

govUkHolidays:
  url: https://www.gov.uk/

azure:
  servicebus:
    host-name: ${AZURE_SERVICE_BUS_HOST_URL}
    topic-name: ${AZURE_SERVICE_BUS_TOPIC_NAME}
    subscription-Name: ${AZURE_SERVICE_BUS_SUBSCRIPTION_NAME}
    retry-duration: ${AZURE_SERVICE_BUS_RETRY_DURATION:60}
    threads: ${AZURE_SERVICE_BUS_CONCURRENT_SESSIONS:1}
    enableASB: ${AZURE_SERVICE_BUS_FEATURE_TOGGLE:false}
    retry-attempts: ${AZURE_SERVICE_BUS_RETRY_ATTEMPTS:3}
