spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15:///databasename
  main:
    allow-bean-definition-overriding: true

scheduledExecutors:
  messageProcessing:
    pollIntervalMilliSeconds: 3000
  messageReadiness:
    pollIntervalMilliSeconds: 3000

logging.level.uk.gov.hmcts.reform.wacaseeventhandler.clients.*: TRACE
logging.level.uk.gov.hmcts.reform: TRACE
