spring:
  datasource:
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:14.5://localhost/wa_case_event_messages_db
    hikari:
      minimum-idle: 1



idam:
  api:
    baseUrl: ${IDAM_URL:http://sidam-api}

role-assignment-service:
  url: http://localhost:8888

document_management:
  url: ${DM_STORE_URL:http://local-dm-store}

ccd_gateway:
  url: ${CCD_GW_URL:http://ccd-api-gateway}

scheduledExecutors:
  messageProcessing:
    threadPoolSize: 1
  messageReadiness:
    threadPoolSize: 1

job:
  problem-message:
    message-id-list: ID:c05439ca-ddb2-47d0-a0a6-ba9db76a3064:58:1:1-10, ID:d257fa4f-73ad-4a82-a30e-9acc377f593d:1:1:1-2704, ID:ce8467a0-cea9-4a65-99dd-3ae9a94a4453:16:1:1-811, ID:04b1809e-c7ca-47d2-90ff-fc95c2e110ab:54:1:1-781, ID:d257fa4f-73ad-4a82-a30e-9acc377f593d:1:1:1-1675
  clean-up:
    delete-limit: 100
    started-days-before: 90
    state-for-prod: PROCESSED
    state-for-non-prod: PROCESSED

retry:
  maxAttempts: 3
  backOff:
    delay: 5000
    maxDelay: 10000
    random: true

environment: local
