java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    POSTGRES_HOST: "{{ .Release.Name }}-postgresql"
    POSTGRES_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    POSTGRES_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    POSTGRES_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    POSTGRES_CONNECTION_OPTIONS: "?stringtype=unspecified"
    POSTGRES_PORT: 5432
    AZURE_SERVICE_BUS_FEATURE_TOGGLE: true
    AZURE_SERVICE_BUS_CONCURRENT_SESSIONS: 1
    MESSAGE_PROCESSING_POLL_INTERVAL_MILLISECONDS: 5000
    MESSAGE_PROCESSING_THREAD_POOL_SIZE: 1
    MESSAGE_READINESS_POLL_INTERVAL_MILLISECONDS: 5000
    MESSAGE_READINESS_THREAD_POOL_SIZE: 1
  postgresql:
    enabled: true
